### ISSUE TITLE
Lite otydligt vid login

### ISSUE THREAD

**Issue by jh222xk** [davidsoderberg/toerh_ds222hz#1]
Jag förstod inte riktigt först att inloggningen var registrering i samma, men om jag har förstått det rätt så skapas en användare om e-posten inte finns, annars så blir man inloggad (användare finns)?

**Comment by davidsoderberg** [comment]
Ja precis

**Comment by jh222xk** [comment]
Jag missade instruktionen över formuläret... Kanske skulle man kunna markera upp den så det blir lite tydligare eller vad tycker du?

**Comment by davidsoderberg** [comment]
Jo kanske jag vet inte, tyckte det va tydligt...

**Comment by jh222xk** [comment]
Ja okej, du gör som du vill :P
