### ISSUE TITLE
Blir utloggad när jag revokar en användares nyckel som admin

### ISSUE THREAD

**Issue by Pajn** [davidsoderberg/toerh_ds222hz#10]
När jag som admin revokear en nyckel blir jag utloggad och måste logga in igen för att revokea en annan användares nyckel.

**Comment by davidsoderberg** [comment]
Tack det skall jag kolla på.

**Comment by davidsoderberg** [comment]
Fixat med commit: https://github.com/davidsoderberg/toerh_ds222hz/commit/5b16e3c880473d98fd309141ed204f1a04935209

**Comment by 1dv450** [comment]
:+1:
