### ISSUE TITLE
Beskriv gärna vilka PHP moduler som krävs

### ISSUE THREAD

**Issue by Pajn** [davidsoderberg/toerh_ds222hz#11]
Förutom att installera php var jag tvungen att installera php-mcrypt och php-mysql för att inte composer.phar skulle krasha. Hade varit trevligt att få veta det på ett annat sätt än ofångade exceptions.

**Comment by davidsoderberg** [comment]
Oj det har nog min xampp installation tagit hand om av sig själv :sweat_smile:
