### ISSUE TITLE
Förvirrande med olika casing på return

### ISSUE THREAD

**Issue by Pajn** [davidsoderberg/toerh_ds222hz#12]
Ibland använder du return och ibland Return. För mig blev det förvirrande och jag fick googla på om det var någon skillnad på de. Att vara mer konsekvent skulle förenkla läsandet och koden, speciellt för det som inte är 100% på PHP och Laravel då man slipper undra om det är någon skillnad eller inte

**Comment by davidsoderberg** [comment]
Yes tänker jag skall köra en search and replace på det sen.
