### ISSUE TITLE
Kommentarer

### ISSUE THREAD

**Issue by 1dv450** [davidsoderberg/toerh_ds222hz#13]
Känns som du fått bra kommentarer av dina peers och eftersom du använder Laravel som kanske inga andra har tittat på blir det svårt att ge feedback direkt på kod mer än övergripande saker. De saker du fått har du dock löst och stängt dessa issues. Bra! Sen är det alltid viktigt med input på sin applikation ifrån hur andra användare ser den.

Jag har aldrig kollat igenom en Laravel-applikation tidigare men man ser vissa likheter med Rails (även om jag syntaxmässigt föredrar Ruby som språk framför PHP).

**Comment by davidsoderberg** [comment]
Och jag tvärtom @1dv450, men smaken är som baken... delad :smile:
