### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by afrxx09** [davidsoderberg/toerh_ds222hz#16]
Aningen otydliga instruktioner, men det gick att installera.

"lägg till php i pathen", tror inte man kan räkna med att många vet vad det betyder.

Hade velat ha mysql-kod för att skapa användaren och tilldela privileges.
Hade velat ha mysql-kod för att skapa databasen.

**Comment by davidsoderberg** [comment]
Jag skall länka till en sida om hur man lägger till php i pathen.
Mysql kod skulle jag kanske kunnat ha inkluderat, det skall jag tänka på :smile:
