### ISSUE TITLE
Skapa "creator"

### ISSUE THREAD

**Issue by afrxx09** [davidsoderberg/toerh_ds222hz#17]
Lyckas inte skapa en "creator", får felmeddelande:

```
"errors": {
        "password": [
            "The password field is required."
        ]
    },
....
```

Vet inte om jag missförstått något men kör "Create creator" i postman filen och det finns ett lösenord där. om jag inte anger en nyckel i requesten får jag ett felmeddelande om det, vilket är korrekt. Så jag kan bara anta att det är något annat skumt som strular till det.

**Comment by afrxx09** [comment]
Har provat både med nyckeln på användaren som jag skapat och nyckeln som fanns i postman från början. Både fungerar att skicka requests med men båda får samma felmeddelande.

**Comment by davidsoderberg** [comment]
Konstigt och jag testade att köra det i en helt ny installation av mitt api och får det att funka on the fly så att säga.
