### ISSUE TITLE
Slutsats

### ISSUE THREAD

**Issue by afrxx09** [davidsoderberg/toerh_ds222hz#18]
Jag kommer tyvärr inte längre än att jag kan skapa ett adminkonto och et vanligt konto efter installationen. Det går logga in men själva API:et kommer jag inte åt.

Kan inte skapa någon creator och alla andra requests säger att användaren inte existerar. Vet inte om jag missuppfattar något. Har försökt gå igenom koden lite men hittar inte vart det går fel.

Något som inte heller framkommer varken i dokumentationen eller applikationen är vad som är api-nyckel och vad som är "token". Jag antar att API-nyckel är det som står längst upr på sidan i den grå rutan när man loggat in. För det är det enda som finns när man loggat in. Sedan ska man få en token när man skapar eller authensierar sin creator som ska användas vid api-requests?

Koden ser väl strukturerad och clean ut. Bra filstruktur som påminner om många MVC-strukturer så man kan ganska snabbt hitta det man söker.

**Comment by davidsoderberg** [comment]
Jag vet inte heller vad du har gjorde för fel. Då jag som jag skrev i ett föregående issue att jag körde en ny installation och fick det att funka on the fly.

Är den här texten otydlig? "token = creatortoken och key = applikationsnyckel".
Båda dessa skall användas när man sen anropar apiet.

En lärdom jag drar av detta är att min readme fil måste vara tydligare och att det är bra att börja med peer reviewn tidigt så man kan lösa sådana här problem som @afrxx09 har haft med mitt api.

Tack för den feedback du kunde ge.
