### ISSUE TITLE
Inloggad, ser inget?

### ISSUE THREAD

**Issue by jh222xk** [davidsoderberg/toerh_ds222hz#2]
När jag först loggade in så såg jag bara detta: 
![bild](http://puu.sh/fOm77/51df5cedc5.png)

Och jag blev då lite förvirrad, så jag hade gärna sett vem jag är inloggad som, samt att det inte finns några användare som har några nycklar om så är fallet.

Nyckeln borde kanske också skrivas ut för administratören?

Annars bra och tydligt att man har sin nyckel som inloggad användare men även samma med att man kanske vill se vem som är inloggad.

**Comment by davidsoderberg** [comment]
Yes skall lösa detta.

**Comment by jh222xk** [comment]
:+1:

**Comment by davidsoderberg** [comment]
Fixat i commiten: https://github.com/davidsoderberg/toerh_ds222hz/commit/9331ae8d7622d2c3576f35f54a24de2a0e6346c4

**Comment by jh222xk** [comment]
Kanon!

**Comment by 1dv450** [comment]
:+1:
