### ISSUE TITLE
Hittar inte din fil med angular-koden

### ISSUE THREAD

**Issue by th222fa** [davidsoderberg/toerh_ds222hz#21]
Jag lyckas inte hitta filen där du har skrivit din angular-kod. När jag tittar i network i chrome developer tools så ser jag att en script.js hämtas från mappen js men när jag kollar där så finns det bara en minifierad fil. Kan ju dock kolla på din kod i developer toolsen.

**Comment by davidsoderberg** [comment]
Här eller på servern?

**Comment by th222fa** [comment]
Hittar inte filen på github

**Comment by davidsoderberg** [comment]
Ah det är den icke uppdelade koden som ligger på servern det är dock ingen skillnad på koden rent programeringsmässigt men första heter login.js och sen är det main.js kolla i public/index.html så ser du vilka js filer som den versionen använder.

**Comment by davidsoderberg** [comment]
Alla js filer ligger här:
https://github.com/davidsoderberg/toerh_ds222hz/tree/master/public/js

**Comment by th222fa** [comment]
aha. Hittade dom nu!
