### ISSUE TITLE
Lite rörig mainCtrl

### ISSUE THREAD

**Issue by th222fa** [davidsoderberg/toerh_ds222hz#24]
Hade varit skönt om du hade delat upp din kod i ytterligare filer för att lättare kunna förstå vad som är vad

**Comment by davidsoderberg** [comment]
Tror att den behöver lite omstrukturering och en större kommentar längst upp så att man där kan läsa sig till vad man hittar i den.

**Comment by davidsoderberg** [comment]
Detta tycker jag att jag har löst i den senaste commiten.
