### ISSUE TITLE
API.js

### ISSUE THREAD

**Issue by th222fa** [davidsoderberg/toerh_ds222hz#28]
Din API.js borde vara en Angular-service, exempelvis en factory. Hade även varit bra om du delade upp inloggningen och eventen i olika filer

**Comment by davidsoderberg** [comment]
Jag hade den uppdelad i två filer från början men då skulle det bara ha blivit två metoder i den ena vilket jag ansåg vara onödigt och la dem i samma. Hade man däremot fortsatt utvecklingen och fyllt på med till exempel glömt lösenord så hade jag gjort det. 

Att jag valde att inte skapa en factory är för att praxis är att inte skicka med scope och så till factoryn och då hade jag fått hantera även det i min controller.
