### ISSUE TITLE
Skapande av nytt event

### ISSUE THREAD

**Issue by th222fa** [davidsoderberg/toerh_ds222hz#29]
När man skapar ett nytt event så är det tänkt att man ska ange latitude och longitude men användare har nog ingen koll på kordinaterna. Land och någon form av adress hade varit bättre om man fick ange. 

När jag skapar ett nytt event, sparar och sen trycker på Create Event så dyker följande feedback upp i modalen: Your event has been created

**Comment by davidsoderberg** [comment]
Ja då har du lyckats att skapa ett event innan detta. Tanken är att man skall kunna ändra lat och long själv men oftast vill man ha den koordinat som står ovanför fälten dessa bör kanske dock vara default också?

**Comment by davidsoderberg** [comment]
Jag valde att sätta dem som default och att ta bort alerts om man öppna modalen igen.
