### ISSUE TITLE
Tas användaren bort vid revoking av nyckel?

### ISSUE THREAD

**Issue by jh222xk** [davidsoderberg/toerh_ds222hz#3]
Verkar som att hela användaren tas bort när man "revokar" en nyckel? Varför händer detta? Borde inte nyckeln försvinna och att man kan skapa en ny nyckel om så önskas?

Nu måste jag skapa ett nytt konto om jag vill ha en ny nyckel?

**Comment by davidsoderberg** [comment]
Japp då man inte önskar att ha en nyckel hos mig längre och därför ser jag ingen nytta med att lagra dem hos mig längre skall förtydliga detta i applikationen.

**Comment by jh222xk** [comment]
Okej, det mesta handlar ju om tyckte och smak. Men att förtydliga det är aldrig fel. :+1:

**Comment by davidsoderberg** [comment]
Jag har nu fettmarkerat user i meddelandet som visas när man tar bort en nyckel.

**Comment by jh222xk** [comment]
:+1:
