### ISSUE TITLE
Adminanvändare

### ISSUE THREAD

**Issue by jh222xk** [davidsoderberg/toerh_ds222hz#4]
Är det inte bättre att ha en boolean i userklassen exempelvis; `is_staff` som är satt till true om användaren ses som en administratör?

https://github.com/davidsoderberg/toerh_ds222hz/blob/master/app/views/index.blade.php#L35

Nu kan du bara ha en användare som administratör samt att det är inte alltid kanske sant att just id 1 ska vara administratör?

**Comment by davidsoderberg** [comment]
Jo då jag bara vill att första användaren skall vara administratör. Detta är inte tänkt att bli så stor och skulle detta ändra så är det inge jätte grej att göra när den är live.
