### ISSUE TITLE
Död kod?

### ISSUE THREAD

**Issue by jh222xk** [davidsoderberg/toerh_ds222hz#5]
Används koden i dessa filer:

https://github.com/davidsoderberg/toerh_ds222hz/blob/master/app/controllers/CreatorController.php#L78-L123

https://github.com/davidsoderberg/toerh_ds222hz/blob/master/app/controllers/EventController.php#L62-L83

https://github.com/davidsoderberg/toerh_ds222hz/blob/master/app/controllers/PositionController.php#L41-L93

https://github.com/davidsoderberg/toerh_ds222hz/blob/master/app/controllers/TagController.php#L53-L105

https://github.com/davidsoderberg/toerh_ds222hz/blob/master/app/filters.php#L14-L23

https://github.com/davidsoderberg/toerh_ds222hz/blob/master/app/views/emails/auth/reminder.blade.php

Till något eller är det bara död kod?

**Comment by davidsoderberg** [comment]
De ligger där för att användas i webb apiet :)
