### ISSUE TITLE
Kommentering

### ISSUE THREAD

**Issue by jh222xk** [davidsoderberg/toerh_ds222hz#6]
Hade gärna sett lite mer kommentering överallt. Exempelvis här hade varit trevligt:

https://github.com/davidsoderberg/toerh_ds222hz/blob/master/app/controllers/UserController.php

**Comment by davidsoderberg** [comment]
Detta skall jag tänka på framöver.

**Comment by Pajn** [comment]
I t.ex. EventController har du bra doc-kommentarer där du förklarar de annars väldigt intetsägande standardnamnen på action-metoderna.
